### ISSUE TITLE
Unable to upload and install

### ISSUE THREAD

**Issue by CodeRed-x** [SkyroomOnline/wordpress-plugin#1]
It wasn't installed due to a fatal error. 

Warning: require_once(/home/websitename/public_html/wp-content/plugins/wordpress-plugin-master/vendor/autoload.php): failed to open stream: No such file or directory in /home/websitename/public_html/wp-content/plugins/wordpress-plugin-master/skyroom.php on line 22

**Comment by mkhahani** [comment]
You need to download from the [releases page](https://github.com/SkyroomOnline/wordpress-plugin/releases), not the source code.
